# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage',
            new_name='Product',
        ),
    ]
