# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20171112_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Shirt', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='red', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=16.5),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Red Blouse with pearls', max_length=50),
        ),
    ]
