# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20171112_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Cotton material', max_length=500),
            preserve_default=False,
        ),
    ]
