# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('productID', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductList'),
        ),
    ]
