# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20171116_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=10),
            preserve_default=False,
        ),
    ]
