# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20171117_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(0, 'Shirts'), (1, 'Dresses'), (2, 'Sweaters'), (3, 'Coat&Jackets'), (4, 'Jeans'), (5, 'Skirts'), (6, 'Shoes')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
