# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
