# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20171129_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirts'), ('Dress', 'Dresses'), ('Sweater', 'Sweaters'), ('Coat', 'Coat&Jackets'), ('Jeans', 'Jeans'), ('Skirt', 'Skirts'), ('Shoes', 'Shoes')], max_length=20),
        ),
    ]
