# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('category', models.CharField(choices=[('Female', (('Shirt', 'Shirts'), ('Dress', 'Dresses'), ('Sweater', 'Sweaters'), ('Coat', 'Coat&Jackets'), ('Jeans', 'Jeans'), ('Skirt', 'Skirts'))), ('Male', (('Tshirt', 'Tshirts'), ('Hoodie', 'Hoodies'), ('MJeans', 'Jeans'), ('MCoats', 'Coats')))], max_length=20)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('size_XS_amount', models.PositiveIntegerField()),
                ('size_S_amount', models.PositiveIntegerField()),
                ('size_M_amount', models.PositiveIntegerField()),
                ('size_L_amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
    ]
