# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('category', models.CharField(choices=[('Shirt', 'Shirts'), ('Dress', 'Dresses'), ('Sweater', 'Sweaters'), ('Coat', 'Coat&Jackets'), ('Jeans', 'Jeans'), ('Skirt', 'Skirts'), ('Shoes', 'Shoes')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=2)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='product_photo')),
            ],
        ),
    ]
