# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20171130_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='postid',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_photo'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
